### PR TITLE
Add GitHub Action running tests

### PR DESCRIPTION
**Pull request by timjb**
(currently, the tests fail)

### CODE REVIEW

**Comment by SReichelt** [comment]
Very nice. Let me make a quick fix for the failing test, then I'll merge it.
BTW, do you think it is possible to somehow run the tutorial in such an environment? Right now, you have to click "Run automatically" manually in the browser (in a debug build). The automatic run needs something that looks like a browser from inside, but it doesn't really need to be an actual browser...

**Comment by timjb** [comment]
I believe that it's definitely possible to run the tutorial as part of some CI job. We could either test the application in a real browser by using some integration testing framework like [Cypress](https://www.cypress.io/) or [Selenium](https://www.selenium.dev/). I don't have any experience with these tools, but would like to try out Cypress. Or we could test our application (and also individual components) using Jest (which uses [jsdom](https://github.com/jsdom/jsdom), an implementation of the DOM and various web APIs in JavaScript) + [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/). I'm using these tools at my job and have my experience is generally positive. There are, however, some limitations to this approach compared to the first:

* Styling/layout is not implemented and therefore you can't test it.
* You can't test navigation between pages.
* There are gaps in the implementation of some APIs and others are not implemented at all.
* When writing or debugging tests, you don't get to see the rendered component/application, which makes the activity more time-consuming than it would otherwise be.

There are also some advantages:

* You can write tests that run quite fast.
* You can write the component tests using the same language (JavaScript/TypeScript) as your application code and other tests.

**Comment by SReichelt** [comment]
> I believe that it's definitely possible to run the tutorial as part of some CI job. We could either test the application in a real browser by using some integration testing framework like [Cypress](https://www.cypress.io/) or [Selenium](https://www.selenium.dev/). I don't have any experience with these tools, but would like to try out Cypress. Or we could test our application (and also individual components) using Jest (which uses [jsdom](https://github.com/jsdom/jsdom), an implementation of the DOM and various web APIs in JavaScript) + [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/). I'm using these tools at my job and have my experience is generally positive.

Both options sound good to me.

Regarding Cypress or Selenium:
* It's especially good to know that Chrome has a headless mode that can be run from GitHub Actions. I believe it already provides most of what we need.
* The testing frameworks seem to be a bit of an overkill for this particular purpose, on the other hand they could be useful for additional real E2E tests later, so it's definitely OK to depend on them.
* In any case, we will need to signal to the app that we are running a test, as the "Run automatically" button is not shown in a production build. E.g. we could use a special route for this. But then this route could be `/test/tutorial`, and it could start the tutorial right away. Then, the only thing that is left to do is to somehow let the tutorial signal that it has finished successfully.
* One caveat with this approach is that it is not so clear (to me at least) how to best run such tests locally. At the moment, running a full build is not required before running tests, but then we need to integrate with `webpack-dev-server` somehow...

Regarding jsdom:
* I hadn't thought about this possibility. It sounds really nice.
* If it works, I think I would prefer it because it integrates better with existing tests.
* A bit of work will be required to make it work because the tutorial kind of depends on everything else. But it could be as simple as instantiating `fileAccessor` with a `PhysicalFileAccessor` in the constructor of the `App` class.

> There are, however, some limitations to this approach compared to the first: ...

I think we might be lucky regarding these limitations, as the tutorial mostly works with React's virtual DOM. The built-in automated test can catch errors resulting from changed rendering or from library refactoring. There are some cases like what happened after updating to React 17 (which you had noticed); these would only be caught by automating the actual user interaction. But the existing automation might work with jsdom.

**Comment by SReichelt** [comment]
FYI, I have added an adapted version of the GitHub action to the library repository, to run a library check on every push: https://github.com/SReichelt/slate-hlm/blob/master/.github/workflows/main.yml

**Pull request merged**
